defaults: &defaults
  # Settings may be over-ridden either in the section below (see the
  # 'development' for examples) or with environment variables such as:
  #
  #    export DATABASE_ADAPTER=sqlite
  database:
    adapter: mysql2
    encoding: utf8
    host: localhost
    username: root
    password: root
    database: hive_ci
    port: 3306
    pool: 5
  job_reservation_timeout: <%= 20.seconds %>
  stuck_running_jobs_timeout: <%= 5.hours %>
  maximum_auto_retries: 1
  hive_mind:
    url: http://localhost:3001
    # cert:
    # cacert:
    # verify_mode:
  testmine:
    url: http://localhost:3002
  test_rail:
    #testrail_account_one:
    #  user:
    #  password:
    #testrail_account_two:
    #  user:
    #  password:
  attachment:
    storage: filesystem
    s3_bucket:
    path_base: public
  sidebar:
  better_errors_for_all: false
  statistics:
    # Chamber does not currently allow arrays to be set from environment
    # variables so for the moment use a comma separated list:
    #   STATISTICS_QUEUES="queue 1,queue 2"
    #   STATISTICS_PROJECTS="queue 1,queue 2"
    queues: queue 1,queue 2
    projects: project 1,project 2

development:
  <<: *defaults
  better_errors_for_all: true
  hive_mind:
    url: http://localhost:3001
  testmine:
    url: http://localhost:3002
  attachment:
    storage: filesystem
    s3_bucket:
    path_base: public

test:
  <<: *defaults
  better_errors_for_all: true
  hive_mind:
    url: http://localhost:3001
  testmine:
    url: http://localhost:3002
  test_rail:
    test_testrail_account:
      user: test_testrail_username@example.com
      password: test_testrail_password
  attachment:
    storage: filesystem
    s3_bucket:
    path_base: public
  sidebar:
    - { label: 'BBC Open Source', link: 'http://www.bbc.com/opensource' }
    - { label: 'BBC', link: 'http://www.bbc.com' }
    - 'divider'
    - { label: 'iPlayer', link: 'http://www.bbc.co.uk/iplayer' }
    - 'divider'
    - { label: 'Queues', link: '/queues' }
    - { label: 'Project 1', link: '/projects/1' }
    - { label: 'Page 7 of batches', link: '/?page=7' }

production:
  <<: *defaults
